### ISSUE TITLE
Broken URL in control panel + Google API billing changes

### ISSUE THREAD

**Issue by darylknight** [doublesecretagency/craft-smartmap#10]
When configuring the plugin, the link to the instructions is a relative URL and therefore doesn't work. 

    <p>To get your Google API keys, <a href="/get-a-google-api-key" target="_blank">follow these instructions...</a></p>

Additional - Google have made changes to their API dashboard and billing requirements. As of July 16th 2018, all uses of the Maps API now require a project with a billing account attached to it. Smart Map docs will be out of date now.

From https://developers.google.com/maps/billing/important-updates
> We began enforcing the use of API keys, effective June 11th 2018. Keyless usage will result in a degraded experience, or an error.

**Comment by lindseydiloreto** [comment]
Hi Daryl, thanks for reporting!

For the first issue, it sounds like you started with an early version of Smart Map for Craft 3. When you installed it, the (now slightly outdated) plugin details got stored in `/vendor/craftcms/plugins.php`. Open up that file and find this information for Smart Map.

What it _should_ look like is this...

```php
  array (
    'class' => 'doublesecretagency\\smartmap\\SmartMap',
    'basePath' => $vendorDir . '/doublesecretagency/craft-smartmap/src',
    'handle' => 'smart-map',
    'aliases' => 
    array (
      '@doublesecretagency/smartmap' => $vendorDir . '/doublesecretagency/craft-smartmap/src',
    ),
    'name' => 'Smart Map',
    'version' => '3.1.1',
    'description' => 'The most comprehensive proximity search and mapping tool for Craft.',
    'developer' => 'Double Secret Agency',
    'developerUrl' => 'https://www.doublesecretagency.com/plugins',
    'documentationUrl' => 'https://www.doublesecretagency.com/plugins/smart-map/docs',
  ),
```

The `version` can & should match the current version of your plugin. Everything else can be updated to match this example. I'm guessing that the `documentationUrl` is empty or missing in your installation.

Regarding the second issue... that's a bit trickier. Google likes to change their entire ecosystem and/or documentation every six months. The Smart Map docs are now partially out of date, but are still somewhat useful for getting Google API keys. I will eventually re-write parts of the documentation, and this page will definitely get addressed at that time.

In the meantime, I've update the plugin's settings page to specify that API keys are now _required_, not _optional_.

Thanks again! 🍺

**Comment by darylknight** [comment]
Thanks Lindsey, now you say that I remember we've had that conversation about documentationUrl before. Thanks!
