### ISSUE TITLE
Error when installing via the `craft` executable

### ISSUE THREAD

**Issue by bwlng** [doublesecretagency/craft-smartmap#11]
Installing Smart Map w/ the `craft` executable ends w/ the following error:

    *** failed to install smart-map: Calling unknown method: yii\console\Response::redirect()

Looks like everything installs fine, but the redirect function in `EVENT_AFTER_INSTALL_PLUGIN` should check whether the install is occurring via the CP or executable.

Smart Map v3.1.1
Craft CMS v3.0.19

**Comment by lindseydiloreto** [comment]
This is now fixed in v3.1.2.

Thanks for reporting! 🍺

**Comment by bwlng** [comment]
Thanks!
