### ISSUE TITLE
Stack all fields on top of each other on mobile

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#12]
Lets say user sets all fields width to 20%. On desktop it will look ok. On mobile, these field contens will be severely trimmed. 
Therefore, i propose adding css breakpoint that would stack all these fields on top each other, if controll panel is displayed on mobile devices.

**Comment by lindseydiloreto** [comment]
This is a great idea!

There's obviously a lot of CSS fanciness happening with the customizable field widths. But I don't see any reason why we couldn't just make all fields 100% below a certain breakpoint.

Thanks for posting! Will leave this open until I get a chance to implement it.

**Comment by lindseydiloreto** [comment]
As of Smart Map v3.2, this is done.

For screens smaller than 360px wide, all subfields will be stacked vertically. This overrides the user's custom subfield sizes.
