### ISSUE TITLE
Option to render small map in smartmap field after selecting location

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#13]
Often, small map would be more meaningfull to editors than seeing just coordinates in smartmap field.
So, after selecting location, such map should appear along with standard smartmap inputs containing coordinates etc.

**Comment by lindseydiloreto** [comment]
Thanks for the feedback. A couple of points to note...

(1) If you click on the "Drag Pin" link, it'll pop up a map of wherever the address has specified. You can then drag the pin (if you want) to make the location even more precise.

(2) My master plan includes an always-visible map next to the address data. Very similar to what you're describing. Not sure when I'll be adding that, probably in the next major release.

Marking this as an "enhancement" for future reference. Thanks again!

**Comment by lindseydiloreto** [comment]
Good news, this is all done in the new [Google Maps](https://plugins.doublesecretagency.com/google-maps/address-field/) plugin! The new Address field is highly configurable...

<img alt="Address field" width="603" src="https://user-images.githubusercontent.com/5309692/109403773-65d9a000-7914-11eb-869b-7a390652a517.gif">
