### ISSUE TITLE
Filter by state or province

### ISSUE THREAD

**Issue by jeffaglenn** [doublesecretagency/craft-smartmap#16]
Is there a way to filter addresses based on state/province alone ( e.g. only returning addresses in California)? It looks like filtering by distance requires a range (whether default or custom) so I'm assuming this is not possible?

**Comment by lindseydiloreto** [comment]
Hi Jeff,

Sounds like you want

**Comment by lindseydiloreto** [comment]
Hi Jeff,

Sounds like you want filtering by a subfield value...

https://www.doublesecretagency.com/plugins/smart-map/docs/filtering-entries-by-subfield-value

You can do this independently of a search, no need to specify a `target` or `range` if you don't need them.

**Comment by jeffaglenn** [comment]
Ah, yes! Should have read the docs a little closer...😞 Thank you!

**Comment by lindseydiloreto** [comment]
No worries!  🙂
