### ISSUE TITLE
Get api key from twig

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#17]
Admin can set up google maps api key in settings, but is it avaible as variable in twig?
If not, i propose adding such variable, otherwise developer has to enter api key two times, one im plugin settings, second one in twig template.

**Comment by lindseydiloreto** [comment]
Good news, that already exists!

```twig
{{ craft.smartMap.serverKey }}
{{ craft.smartMap.browserKey }}
```

Here's the (very simple) code behind it...

https://github.com/doublesecretagency/craft-smartmap/blob/v3/src/variables/SmartMapVariable.php#L102-L112

**Comment by piotrpog** [comment]
@lindseydiloreto great, thanks.
