### ISSUE TITLE
Does the plugin support caching of Geocoding results?

### ISSUE THREAD

**Issue by nilsenpaul** [doublesecretagency/craft-smartmap#18]
With Google Geocoding being a paid service, does SmartMap offer a way to cache the Geocoding results? Our visitors search by (proximity to) a city, so the same City geocoding request goes to Google over and over ...

**Comment by lindseydiloreto** [comment]
Ironically, _it used to_ get cached. When I ported the plugin to Craft 3, that was the one tiny feature that got omitted, because I ran out of time.

Now that Google has completely changed their billing structure, it's become an important feature again. I'll look into re-introducing it soon.

**Comment by nilsenpaul** [comment]
That would be nice, thanks!

**Comment by nilsenpaul** [comment]
Any news on this? Google bills are not funny, hoping to reduce them a bit ...

**Comment by nilsenpaul** [comment]
What would make me love you even more, is an implementation of this OpenStreetMap's [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) 👍

**Comment by lindseydiloreto** [comment]
I'm working on a Smart Map update right now, I may be able to fix the caching issue while I'm in there. Hopefully it all goes smoothly, and I'll have an update out within the next few weeks.

Thanks for the tip on Nominatim, I'd never heard of that! I'll work it into some future plans. 😉

**Comment by lindseydiloreto** [comment]
Good news! I've just released Smart Map **v3.2.0**, which caches the results of two significant lookups:
 - Geolocation lookups (ipstack, MaxMind)
 - Search target lookups (Google Maps API)

For more info, check out the [changelog...](https://github.com/doublesecretagency/craft-smartmap/blob/v3/CHANGELOG.md#320---2018-12-06)
