### ISSUE TITLE
smartmap field inside supertable looks bad

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#19]
When i put smartmap field into supertable field (using table layout), thats what i get:
https://imgur.com/a/4YwDfrA

This is small css snippet i made for myself, not ideal, but fixes it a little:

```
div.smartmap-field{
        display: flex;
	align-items: center; 
}

div.smartmap-top-right{
        position: static;
	order: 2;
	width: 30%;
}
```

**Comment by lindseydiloreto** [comment]
Thanks for the heads up, and for the CSS snippet.

I'll try to make this change during the next round of updates. 👍

**Comment by piotrpog** [comment]
@lindseydiloreto I suggest just changing text links to icon links, they would take much less space.

**Comment by lindseydiloreto** [comment]
Interesting idea. I may explore icons for a future version.

**Comment by lindseydiloreto** [comment]
This is (technically) done. As of Smart Map v3.2, we've improved compatibility with Super Table...

<img width="361" alt="Super Table + Smart Map" src="https://user-images.githubusercontent.com/5309692/49422333-56c11300-f748-11e8-8839-b70f88251da6.png">

I like the idea of using icons in place of these long text strings. We'll keep this thread open until I eventually swap them out for icons.

**Comment by lindseydiloreto** [comment]
Closing in favor of #23
