### ISSUE TITLE
Using Craft's web request within the SmartMapService

### ISSUE THREAD

**Issue by dsmrt** [doublesecretagency/craft-smartmap#2]
Not sure if this is the right place to submit this bug but here I am.

I use the Craft's CLI regularly and love your plugin but I just ran into a problem with the SmartMapService here: https://github.com/doublesecretagency/craft-smartmap/blob/v3/src/services/SmartMapService.php#L364

You are checking for if the request is post (`Craft::$app->request->getIsPost()`) and this breaks when using the cli. Those types of checks are probably more appropriate for the web controller.

**Comment by lindseydiloreto** [comment]
Good catch, thanks! I'll make some adjustments, and report back here when it's done.

**Comment by dsmrt** [comment]
Thanks Lindsey! Love the plugin!

**Comment by lindseydiloreto** [comment]
Hey Damien, this should be fixed in v3.0.2... Go ahead and update when you get a chance!
