### ISSUE TITLE
Save zoom level when saving map info

### ISSUE THREAD

**Issue by piotrpog** [doublesecretagency/craft-smartmap#20]
For every smartmap field i also need to add zoom field. Why not just save in database zoom level that is set during placing marker on map using "drag pin" option?

**Comment by lindseydiloreto** [comment]
The Smart Map field is just an address, it is not meant to represent a whole map. You can have multiple locations on the same map. There are many variations to rendering map data.

In the Craft control panel, you can easily add a "Zoom" field, and place it beside the address field.

**Comment by piotrpog** [comment]
Problem with numeric zoom field is that its not intuitive. 
With optipn to save zoom level from map, user would actually see how his map would look like

**Comment by lindseydiloreto** [comment]
That's interesting.

I'll leave this open as a feature request. I may roll it in if/when the address field gets a big overhaul.

**Comment by lindseydiloreto** [comment]
This is done in the new [Google Maps](https://plugins.craftcms.com/google-maps) plugin! The `zoom` value is now a standard part of the [Address Model](https://plugins.doublesecretagency.com/google-maps/models/address-model/).

You can see the new **Zoom** subfield next to the coordinates in the graphic below...

<img alt="Annotated Address Field" width="800" src="https://user-images.githubusercontent.com/5309692/109345523-24b69280-7825-11eb-8477-e0dc7cf325c8.png"/>
