### ISSUE TITLE
Field values are not translatable/multi-site, despite options showing

### ISSUE THREAD

**Issue by timkelty** [doublesecretagency/craft-smartmap#21]
If the field is not multi-site capable (which it doesn't appear to be), you should have a `supportedTranslationMethods` method returning an empty array, or `[self::TRANSLATION_METHOD_NONE]`.

See https://github.com/craftcms/cms/blob/develop/src/base/Field.php#L89-L98

![screen shot 2018-10-18 at 7 19 11 am](https://user-images.githubusercontent.com/18329/47150894-20b5f580-d2a6-11e8-81e9-147b16502195.png)

**Comment by timkelty** [comment]
Once this is released, this will be fixed automagically :) https://github.com/craftcms/cms/commit/106c42ef3cce27b62037c3d923a8d72f7cec00b1

**Comment by lindseydiloreto** [comment]
Sweet, thanks @timkelty! 🍺
