### ISSUE TITLE
Make field translatable/multi-site capable

### ISSUE THREAD

**Issue by missmatsuko** [doublesecretagency/craft-smartmap#22]
Related issue: #21

I'd like to have addresses spelled differently depending on the locale.
For example, "P.O. 123" in English would be "C.P. 123" in French for the same address (because Canada).

I saw this page as well, but I don't think it's helpful for this situation:
https://www.doublesecretagency.com/plugins/smart-map/docs/internationalization-support

**Comment by myriago** [comment]
. Outside of translations I often need a different address for different sites (on multi-site) which currently isn't possible. I want to be able to have translatable field in globals to set up each sites main address.

**Comment by lindseydiloreto** [comment]
Hmm... I've been trying to wait until the next major release to address this, but it looks like I may not be able to wait that long.

I'll take a look into this soon. Thanks for the additional info!

**Comment by myriago** [comment]
Any idea when that would go live? Not pushing just want to know how to go about on my current project.

**Comment by lindseydiloreto** [comment]
@myriago Hard to say. I doubt it would be in the _immediate_ future, but I'll try to bump it up the priority list.

**Comment by dsmrt** [comment]
+1 I have a microsite setup that needs this

**Comment by jamiewade** [comment]
@lindseydiloreto Any updates on this?

**Comment by lindseydiloreto** [comment]
@jamiewade I'm currently in the middle of a giant project which has consumed most of my attention, though this feature request has not completely dropped off my radar.

Once that project is wrapped up (within the next couple of months), I intend to circle back around and give Smart Map a bit of love. This particular feature request is near the top of the list. 👍

**Comment by lindseydiloreto** [comment]
Just FYI to everyone following this thread...

This issue is still one of the higher priorities for Smart Map. It didn't make it into the recent 3.3 release, unfortunately, but I fully intend to address it in the next major version. 🙂

**Comment by lindseydiloreto** [comment]
This issue has been migrated to the Google Maps repo. To stay up-to-date, subscribe over there...

 - https://github.com/doublesecretagency/craft-googlemaps/issues/11
