### ISSUE TITLE
Get Directions method needs updating

### ISSUE THREAD

**Issue by damienbuckley** [doublesecretagency/craft-smartmap#24]
The craft.smartMap.directions method in SMart Map v3.1.3 needs updating for the current Google API - its not rendering anything. This works for me:- `<a href="https://www.google.com/maps/dir/?api=1&destination={{ element.physicalAddress.street1 }}+{{ element.physicalAddress.city }}+{{ element.physicalAddress.state }}+{{ element.physicalAddress.zip }}" target="_blank">`

**Comment by lindseydiloreto** [comment]
You're in luck... I just released Smart Map **v3.2.0**, which [specifically addresses](https://github.com/doublesecretagency/craft-smartmap/blob/v3/CHANGELOG.md#320---2018-12-06) the `directionsUrl` method.

Go ahead and `composer update` when you get a chance! 🍺

**Comment by damienbuckley** [comment]
Love your work!
