### ISSUE TITLE
What are the limitations for the trial version?

### ISSUE THREAD

**Issue by JayBox325** [doublesecretagency/craft-smartmap#26]
Hi,

I am just wondering what the limitations for the Trial version of the plugin are? We have setup two Google APIs as per your documentation and included them in the CMS, however when I try to run a search for an address the CMS throws and error as follows: `This API project is not authorized to use this API.`

Any advice would be welcome.

Thanks,
Jay

**Comment by JayBox325** [comment]
This has been resolved. We just had to enable a few more API features and it worked through a single unrestricted key where two keys weren't working before.

It'd still be interesting to add some notes in the docs about any potential drawbacks to the trial version.

**Comment by lindseydiloreto** [comment]
Hi Jay,

Good news, there are zero differences between the trial version and regular version! The only thing you'd ever see is an "unlicensed" message in the Craft CP if you launched it without purchasing. Other than that, you've got 100% of the functionality available to you. 👍
