### ISSUE TITLE
Visitor array not returning 'coords' key

### ISSUE THREAD

**Issue by missmatsuko** [doublesecretagency/craft-smartmap#27]
The [Visitor Geolocation page in the docs](https://www.doublesecretagency.com/plugins/smart-map/docs/visitor-geolocation) say:

```
The "visitor" array will contain the following keys:

- ip
- city
- state
- zipcode
- country
- latitude
- longitude
- coords
```

I'm not getting a `coords` item when I dump `craft.smartMap.visitor`.

It might be because the rest of the keys returned null for this IP, but I still expected the `coords` key to exist with null, too.

Not sure what it's supposed to be with a good IP, but I expected it to be a string form of `latitude` and `longitude` with a comma separation.

**Comment by lindseydiloreto** [comment]
Hi @missmatsuko, which version of Smart Map are you running?

**Comment by missmatsuko** [comment]
- Smart Map 3.2.0
- ipstack for geolocation
- Craft CMS 3.0.34

**Comment by lindseydiloreto** [comment]
Hmm, that's pretty strange. It should at least be set to `false` by default...

https://github.com/doublesecretagency/craft-smartmap/blob/v3/src/services/SmartMapService.php#L66

The whole geolocation mechanism is being replaced in a future version of Smart Map, so it's probably not worth a ton of energy to investigate now. I'm not sure what's happening, but I won't have any near-term availability to look deeper into it.

In the short term, I'd say to just code defensively around it. Worst case scenario, you can manually build the coordinates with `latitude` and `longitude`.

Sorry, hope that helps!
