### ISSUE TITLE
Link to URL is relative to installation in plugin documentation

### ISSUE THREAD

**Issue by jasonmccallister** [doublesecretagency/craft-smartmap#28]
This is related to #10. 

However, I did not have an existing installation. I have a new version of Craft (recently installed) and then installed Smart Map. I'm getting a relative path to the documentation for getting a Google API key.

![screen shot 2019-01-18 at 12 30 18 pm](https://user-images.githubusercontent.com/5354908/51403049-465cd000-1b1d-11e9-9411-e16606fb107d.png)

**Comment by lindseydiloreto** [comment]
Hey @jasonmccallister! Weird, that definitely shouldn't be happening. It looks like it's working normally on this (relatively) new site of mine...

<img width="1015" alt="2019-01-18 at 10 19 28 am" src="https://user-images.githubusercontent.com/5309692/51405255-b3b33580-1b0a-11e9-9bdc-c16b1ef78ab3.png">

Take a look at `/vendor/craftcms/plugins.php`. Did the `documentationUrl` value get properly populated?

<img width="663" alt="2019-01-18 at 10 22 03 am" src="https://user-images.githubusercontent.com/5309692/51405355-fb39c180-1b0a-11e9-8afc-3fe87d098b79.png">

I wonder if this has anything to do with Craft 3.1... I haven't yet had a chance to test much with the new release.

**Comment by lindseydiloreto** [comment]
This has been fixed in **v3.2.2**

I just hard-coded the full URL, instead of trying to be clever with the `plugins.php` file. ¯\\\_(ツ)_/¯
