### ISSUE TITLE
Improve field styles when shown in edit element HUDs

### ISSUE THREAD

**Issue by carlcs** [doublesecretagency/craft-smartmap#29]
<img width="611" alt="bildschirmfoto 2019-01-23 um 17 30 19" src="https://user-images.githubusercontent.com/7516543/51621357-a0ea9780-1f34-11e9-8951-639aacbf32e9.png">

**Comment by lindseydiloreto** [comment]
Thanks for the heads up!

**Comment by lindseydiloreto** [comment]
This has been fixed in **v3.2.2**

Thanks again for reporting!
