### ISSUE TITLE
FilterCriteria::target attribute does not exist on model

### ISSUE THREAD

**Issue by nateiler** [doublesecretagency/craft-smartmap#3]
https://github.com/doublesecretagency/craft-smartmap/blob/73dcc9df02f3786b47f4f3bdf52163944102750d/src/services/SmartMapService.php#L407

I'm trying to return results using haversine from explicit geo coordinates.     

This is what I'm passing
```
$elementQuery->address([
    'target' => ['lat' => 40.8, 'lng' => -87.3,
    'range' => 200
])->orderBy('distance');
```

The 'target' attribute is getting interpreted properly, but the attribute itself isn't getting removed from the array and therefore throwing an error when creating the `FilterCriteriaModel`.

You could probably do an `ArrayHelper::remove` to get a `$target` and do what you need from there.

**Comment by lindseydiloreto** [comment]
Hey Nate, thanks for the heads up!

I'm partially understanding what your talking about... and if I understand correctly, your solution makes perfect sense.

I'll hit you up on Craft Slack first though, to get clarification before I make any changes. 👍

**Comment by lindseydiloreto** [comment]
After chatting on Slack, sounds like this was a non-issue.
