### ISSUE TITLE
Url Encode Address when Geocoding

### ISSUE THREAD

**Issue by nateiler** [doublesecretagency/craft-smartmap#31]
It's somewhat common that an address consists of some characters that aren't 'url safe'.  The common one we see is the '#' used to represent an office or mail box number.

Example:
123 Main St. #211
San Francisco, CO 94105

The result is a api url which consists of '#' and resulting in, you guessed it, everything behind the # getting stripped by the server resulting in an error.

Suggest url encoding the address prior to sending:
https://github.com/doublesecretagency/craft-smartmap/blob/57a3e2cbc0b44b902141eadc87d00bc97ff28565/src/services/Main.php#L33

**Comment by lindseydiloreto** [comment]
Ahh, interesting! Thanks for flagging that @nateiler.

I'll try to get a fix in an upcoming version. 👍

**Comment by lindseydiloreto** [comment]
This has been fixed in **v3.2.2**
