### ISSUE TITLE
Feature request: add support for CraftQL

### ISSUE THREAD

**Issue by keithmancuso** [doublesecretagency/craft-smartmap#4]
We've been using [mark's new CraftQl plugin ](https://github.com/markhuot/craftql) but hit a wall because of support for the smart map fieldtype!

he has a documented way to add support for the fieldtype which seems pretty straightforward. Any chance you'd consider adding this?

https://github.com/markhuot/craftql#third-pary-field-support

[Mark had shown how to do it with a similar map plugin ](https://github.com/markhuot/craftql/issues/30)but I still like smart map better!  Dont make me switch, lol!

**Comment by lindseydiloreto** [comment]
On the roadmap already! I'll try to get it added soon-ish.

The whole GraphQL/CraftQL thing is still pretty new to me, so there might be a slight learning curve here.

**Comment by lindseydiloreto** [comment]
Added in v3.1.0 👍
