### ISSUE TITLE
Sorting by lat/lon is not working via template

### ISSUE THREAD

**Issue by anderthalb** [doublesecretagency/craft-smartmap#45]
Hi there,

I followed your help page for "Sorting entries by closest locations" but I can't get it to work.

I created an address-field (handle: "adresse") and stored correct data into it (with lat/lon!).

Then I added your code to a twig template (slightly altered):

```
{% set target = craft.request.getParam('q') %}

{% set params = {
    target: target,
    range: 100
} %}

{% set entries = craft.entries.section('places').adresse(params).orderBy('distance').all() %}

<h1>Showing results for "{{ target }}"...</h1>
{% for entry in entries %}
    <h2>{{ entry.title }}</h2>
    <div>
        {{ entry.adresse.street1 }}<br />
        {{ entry.adresse.city }} {{ entry.adresse.zip }}<br>
        <strong>{{ entry.adresse.distance | number_format(1) }} miles away</strong>
    </div>
{% else %}
    <h2>No results found</h2>
{% endfor %}
```

I think I'm missing an important step, but I can't see it. Do I obligatory need a google maps key? I haven't added one.

If I remove the part ```.adresse(params).orderBy('distance')```from the query, I get all entries. So in general, the query is ok.

Any help is appreciated.

Thanks and Cheers, Christian

**Comment by anderthalb** [comment]
FYI: I just added a google key for backend & frontend (which worked, as I can see on the debug-page) and cleared all caches. Still not working.

**Comment by anderthalb** [comment]
Ok, never mind :-) I looked through the log-files and found an error `[doublesecretagency\smartmap\services\SmartMapService::lookup] Google API error: This API project is not authorized to use this API.`.

After some digging I noticed some wrong settings in google cloud for my keys. So it was a google key error after all.

This issue can be closed.

Cheers, Christian

PS: Maybe you want to update your docs and add a remark about the importance of using a google key

**Comment by lindseydiloreto** [comment]
Hi @anderthalb,

There's a notice at the top of the [Get Google API keys](https://www.doublesecretagency.com/plugins/smart-map/docs/get-google-api-keys) page which mentions that API keys are now required.

<img width="662" alt="Ω 2019-08-02 at 2 41 45 PM" src="https://user-images.githubusercontent.com/5309692/62391759-b1a74600-b533-11e9-8752-a2330279361f.png">

Glad you got it all sorted out! 🙂
