### ISSUE TITLE
Allow field export in Craft 3.2 native export

### ISSUE THREAD

**Issue by jeffaglenn** [doublesecretagency/craft-smartmap#46]
It looks like when I export entries with a Smartmap field the field does not get exported. However, it seems like there are even some native fields that don't get exported so I didn't know how Craft handles this. 🧐

**Comment by lindseydiloreto** [comment]
Interesting, good catch! The data is stored in a 3rd-party table, so I guess I shouldn't be shocked.

I'll take a look when I get a chance. Thanks for reporting!

**Comment by chadwells** [comment]
Hello,

Any updates on this? Would love to be able to export Smart Map address fields using the Craft Export tool. This is a hot issue within my organization. (Haven't yet had a chance to look at the updated Export features in Craft 3.4)

**Comment by lindseydiloreto** [comment]
Hi @chadwells,

I'm working on some significant updates for Smart Map right now, and I plan to address the field exports as part of that release. I don't have an ETA per se, but I'm aiming for sometime in the next 2-3 weeks. 🤞

**Comment by lindseydiloreto** [comment]
@jeffaglenn @chadwells This feature has been added to the `v3-dev` branch. 👍

It's now possible to select an **Address (Smart Map)** export type. That will give you separate columns for all of the subfields on each of your Address fields.

<img width="236" alt="Ω 2020-03-11 at 12 07 16 AM" src="https://user-images.githubusercontent.com/5309692/76391763-6658df80-632d-11ea-8769-0029bc7b4808.png">


To start using this feature now, switch Smart Map to `dev-v3-dev` in your composer.json file...

```
"doublesecretagency/craft-smartmap": "dev-v3-dev"
```

Let me know if you have any questions!

**Comment by jeffaglenn** [comment]
Fantastic! Thanks Lindsey, I'll check it out.

**Comment by chadwells** [comment]
Thanks Lindsey. This seems to work really well so far.

**Comment by lindseydiloreto** [comment]
Excellent! Thanks for reporting back. 🍺
