### ISSUE TITLE
Allow Customized Content (email, phone) in the address object

### ISSUE THREAD

**Issue by xhuang9** [doublesecretagency/craft-smartmap#47]
I will be great to have the ability to attach customised field (Email, Phone) attach to the address object.

Most of our clients have multiple stores, they have multiple contact information like phone, email. Right now I have to create a matrix field and put a "smart map address field" with an email text field and phone text field, and set smart map address field to only allow one address. And treat each matrix blocks as a store object.

If smart map object can have phone and email in it, I can directly use smart map object as my store. It will save lots of configuration time and run time query resource.

Version:
Smart Map 3.2.2.1
Craft: 3.3

**Comment by xhuang9** [comment]
Sorry, I think I made some mistake. I thought smart map object works like a matrix. Turns out its just a plain text field. We would have to wrap it in matrix to allow multiple address anyway.

**Comment by lindseydiloreto** [comment]
Yup, that's exactly right! You can use Smart Map in a Matrix field to get the effect you are looking for. 🙂
