### ISSUE TITLE
Get Directions method error

### ISSUE THREAD

**Issue by E2design** [doublesecretagency/craft-smartmap#49]
Using SmartMap 3.2.2.1 on Craft Pro 3.3.18.3.
Template is rendering correct including a markerInfo set-up
However adding a button link to the Google directions page trows a template error: Calling unknown method: craft\elements\db\EntryQuery::directionsUrl()

```twig
<div class="uk-margin">
    {{ craft.smartMap.map( entry.vestiging, options ) }}
    {# Load Snazzy Maps via Twig #}
    {% include '_includes/js/snazzy-map.twig' %}
    {# Automatically detect user's starting location #}
    <a class="uk-button uk-button-default uk-margin-top" href="{{ entry.vestiging.directionsUrl }}&amp;saddr=Current+Location" target="_blank">Zoek de route in Google Maps</a>
</div>
```

**Comment by lindseydiloreto** [comment]
Hi there,

What kind of field is `vestiging`? It's claiming that `entry.vestiging` is an EntryQuery... Is that a relationship field for another section?

**Comment by E2design** [comment]
Yes that is a relationship field to another section 'vestigingen'. In which the field 'vestigingAdres' is the SmartMap field.

**Comment by lindseydiloreto** [comment]
That makes sense. So then `entry.vestiging.directionsUrl` won't work.

Assuming you just want to get directions to the _first_ related entry, it would probably look something like this...

```twig
{# Get the first related entry #}
{% set relatedEntry = entry.vestiging.one() %}

{# Output the directions URL of the Address field in that entry #}
{{ relatedEntry.vestigingAdres.directionsUrl }}
```

Hope that helps!

**Comment by E2design** [comment]
It sure did! Appreciate your support :-)
