### ISSUE TITLE
Make compatible with CP Field Inspect

### ISSUE THREAD

**Issue by lindseydiloreto** [doublesecretagency/craft-smartmap#5]
Minor overlapping text...
<img width="827" alt="gear above right corner" src="https://user-images.githubusercontent.com/5309692/38585668-855aade0-3ccf-11e8-84d4-31f6b6a1d7fc.png">

**Comment by timkelty** [comment]
yes, please!

**Comment by lindseydiloreto** [comment]
As of Smart Map v3.2, this is fixed.

<img width="277" alt="Smart Map + CP Field Inspect" src="https://user-images.githubusercontent.com/5309692/49424940-f97d8f80-f750-11e8-92fd-910f36226f2a.png">
