### ISSUE TITLE
Deprecation error after upgrade to PHP 7.4.1

### ISSUE THREAD

**Issue by alsessions** [doublesecretagency/craft-smartmap#50]
After updating to PHP 7.4.1 I receive an error on previously working maps.

```array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead```

Pastebin of stack trace: https://pastebin.com/0cngYV7r

**Comment by lindseydiloreto** [comment]
This is fixed for the next release of Smart Map. If you want it now, change this line in your `composer.json` file and run `composer update`...

```
"doublesecretagency/craft-smartmap": "dev-v3-dev"
```

Thanks for reporting it! 👍
