### ISSUE TITLE
Addresses selected from Google which contain apostrophes get output with symbol entities

### ISSUE THREAD

**Issue by zizther** [doublesecretagency/craft-smartmap#52]
If I perform an address lookup to get the details from Google's API it will either enter or replace the content in the fields with content containing HTML symbol entities, rather than the corresponding character.

**Comment by lindseydiloreto** [comment]
Huh, interesting. Thanks for the heads up, I'll take a look into it!

**Comment by lindseydiloreto** [comment]
I'm having trouble replicating this. Can you give me an example of an address that was causing this problem? How exactly were you using the address?

**Comment by lindseydiloreto** [comment]
Found a good test string: `Rue de l'Escarpe`

This is now fixed, and will go out with the next release.

**Comment by zizther** [comment]
Thanks, sorry I couldn't get back to you on your point. Appreciate the fix.
