### ISSUE TITLE
Not compatible with PHP 7.4

### ISSUE THREAD

**Issue by AndrewMac** [doublesecretagency/craft-smartmap#53]
Hello there, I was testing a site recently to see if it could be moved to PHP 7.4, and I ran into some errors that seemed to come from Smart Map—apologies that I don't have the exact error message to hand at the moment, but I'll try to post them soon.

In any case, I was just wondering if Smart Map had yet been tested with 7.4, or if there was a plan to do so. And if you have indeed tested and found any issues, do you happen to know how long it might take to get them fixed.

Thanks in advance for any help or advice you may be able to give with this.

Andrew Macpherson

**Comment by lindseydiloreto** [comment]
Good news, I've actually already made some fixes with regards to PHP 7.4 compatibility!

Those changes haven't yet been publicly released, but you can get them now by switching to the `v3-dev` branch in composer...

```
"doublesecretagency/craft-smartmap": "dev-v3-dev"
```

If you still have issues, just report them back here and we can reopen this thread.

I plan to formally release these changes within the next 2-4 weeks. 👍

**Comment by AndrewMac** [comment]
Hi Lindsey

I'm afraid that, even running dev-v3-dev, I'm still having an error that seems to be from SmartMap. I'll paste the code and upload the error messages below.

This issue occurs whenever I load a map in Craft Pro 3.4.3 under PHP 7.4 ... but everything works just fine if I switch back to PHP 7.3.9.

Thanks in advance for any help or advice you may be able to give with this.

First the code:

```
<div id="map">
	{% set options = {
		mapType: 'hybrid',
		zoom: 9,
		draggable: false,
		markerInfo: 'include/mapInfoBubble',
		markerOptions: {
		icon: 'https://maps.google.com/mapfiles/ms/icons/orange-dot.png'
		},
		infoWindowOptions: {
		maxWidth: 200
		}
	} %}
	{{ craft.smartMap.map(entry.address, options) }}
</div>
```

And now the error message:

[smart-map-error.txt](https://github.com/doublesecretagency/craft-smartmap/files/4152446/smart-map-error.txt)

[smart-map-error.docx](https://github.com/doublesecretagency/craft-smartmap/files/4152451/smart-map-error.docx)

And, just for good measure, the error if I go to the Smart Map 'debug' page:

[smart-map-debug.docx](https://github.com/doublesecretagency/craft-smartmap/files/4152473/smart-map-debug.docx)

**Comment by lindseydiloreto** [comment]
Moved conversation to #54
