### ISSUE TITLE
Still incompatible with PHP 7.4

### ISSUE THREAD

**Issue by AndrewMac** [doublesecretagency/craft-smartmap#54]
Just creating a new issue just in case you didn't get any notification that  I added a comment to the issue you closed recently: https://github.com/doublesecretagency/craft-smartmap/issues/53

I’m afraid that the Smart Map dev-v3-dev branch you suggested didn’t solve the issue I’m having under PHP 7.4. 

Below I have attached the error I get if I load the Smart Map debug page—it's the same error that appears on front-end map pages. It returns 'internal server error' if dev mode is turned off, so any page that loads a Smart Map is not rendering at all on live sites.

[smart-map-debug.docx](https://github.com/doublesecretagency/craft-smartmap/files/4179062/smart-map-debug.docx)

Thanks in advance for any help or advice you may be able to give with this.

Andrew Macpherson
Sydney, Australia

**Comment by lindseydiloreto** [comment]
Good timing, I literally just pushed a fix for this a few minutes ago. It took me several days of untangling the problem to sort it out.

It basically boiled down to a weird mix of these things...
 - PHP 7.4
 - You're running in a local environment.
 - A general bug in the geolocation process.
 - A specific bug in the ipstack service.

All of those things should be resolved though. Go ahead and pull on the dev branch again, let me know if that fixes it for you.

**Comment by AndrewMac** [comment]
Hi Lindsey

Thanks so much for your help with all this; I really appreciate it!

That most recent dev version did indeed fix things ... well, mostly, at least ;-)

First, the good news: it's now working just fine on the PHP 7.4.2 production server, with everything back to normal. Things are exactly as they used to be.

The not-quite-so-good news, albeit of much less importance, is that the local instance (PHP 7.4.1 on MAMP Pro) is still behaving a little strangely, across Firefox, Chrome and Safari. The PHP error has gone, but instead of the map it now just displays the text "Loading map...". 

It seems to be a JavaScript issue, but I'm not honestly sure why, particularly since everything starts working again if I set the local environment back to PHP 7.3. 

Here are the console messages from 7.4:

<img width="687" alt="CleanShot 2020-02-10 at 19 42 40@2x" src="https://user-images.githubusercontent.com/70342/74133838-8bc6d080-4c3d-11ea-82df-d74442d87a4f.png">

It's all a bit curious, but I can live with things as they are. The important thing is that the production version is now working, so I've been able to turn the maps back on.

Thanks again
Andrew

**Comment by AndrewMac** [comment]
Hi Lindsey

Actually, forget the last message. I think it was a temporary issue only ... everything seems fine now, even on the local site :-)

I reckon it's okay to close this once again. And thanks, again, for all your help!

Cheers
Andrew

**Comment by lindseydiloreto** [comment]
Awesome, glad you got it sorted! 👍
