### ISSUE TITLE
Region Biasing isn't working as intended

### ISSUE THREAD

**Issue by darylknight** [doublesecretagency/craft-smartmap#56]
Region biasing doesn't seem to be working the way the docs say it should.

If I search for "venice" like in the docs and my code is:

`{% set params = { target: "Venice", range: 20, units: 'miles', components: {'country': 'US', 'administrative_area': 'California'} } %}`

The docs say it should return the Venice in California, but it's still showing the one in Italy.

![image](https://user-images.githubusercontent.com/1250017/81169727-ff108200-8fa1-11ea-8e18-9534ee650891.png)

Setting `components: { 'country': 'US' }` should actually stop anything that isn't in the US from showing up at all according to Google. I know we can only bias administrative area, but you can still force results within a specific country.

**Comment by lindseydiloreto** [comment]
Hmm, that sounds unusual. Let's chat it out on Discord, and we'll report our findings back here. 👍

**Comment by darylknight** [comment]
Updating for benefit of others; not a Smart Map issue!

The problem was with the order of my code and how I was centering the map manually. So the results returned from Smart Map were correct, but I also have code adding a grey pin for the coordinates of the search target if there are no results. The code to render the map if there were no results wasn't focusing on the US, just the coordinates of whatever was entered.

**Comment by lindseydiloreto** [comment]
Ha, it happens! Thanks for reporting back @darylknight. 🍺
