### ISSUE TITLE
Address lookup is returning Country name in State field, not the state name

### ISSUE THREAD

**Issue by johnwbaxter** [doublesecretagency/craft-smartmap#57]
Hey Lindsey,

When doing a address lookup via the fieldtype, it's finding the address ok, but it shows in the sate field "England" and Country "United Kingdom". The state should be "Oxfordshire" or whatever, not England.

When I click to select the address I want, it fills in the address fields with "England" in the "Sate" field too.

Any lead on why this is happening?

Thanks!

John

**Comment by lindseydiloreto** [comment]
Hey John! Which version of Smart Map are you running?

If you’ve recently updated, did the problem exist _before_ you updated?

**Comment by johnwbaxter** [comment]
Hey Lindsey!! :wave: 

This is a new ( to me) site wot I have picked up that was using a competitors map plugin (wont mention names) and I have put yours in cos theirs sucks!

So, it's brand new 3.3.2 as of today!

Thanks :)

John

**Comment by lindseydiloreto** [comment]
Ha, we all appreciate your discretion. 😉

Interesting, I don't recall having many complaints from our UK clientele. Is this happening with all UK addresses, or does it seem to be contained to a specific region?

**Comment by johnwbaxter** [comment]
We were only looking at UK locations for this site, so it's all UK addresses across lots of different regions.

**Comment by philipboomy** [comment]
I can confirm a little issue with UK search - See this video for more info https://share.getcloudapp.com/nOukW96Y

It inputs "England" in State/County and some times miss the City. I tried with "10 downing street" and this is that I got https://share.getcloudapp.com/P8ubl6x4 and https://share.getcloudapp.com/9ZuXWDee

According to Google Maps then this is the full address
https://www.google.com/maps/place/10+Downing+St,+Westminster,+London+SW1A+2AB,+UK/data=!4m2!3m1!1s0x487604c56a6cc61d:0x2eca1ef309dd9534?sa=X&ved=2ahUKEwjniY-X04jrAhWl2-AKHVY_CZ0Q8gEwAXoECAsQAQ

Craft CMS 3.5.1
Smart Map 3.3.3
PHP version 7.4.8

Appreciate all the work you have put into this plugin.

**Comment by lindseydiloreto** [comment]
Thanks for confirming, and thanks for the video! That's actually pretty helpful.

So what _should_ those values be? What should be appearing in the "Town/City" and "County" fields?

Sorry, as a dumb American, British geography is incredibly confusing to me. 🙃

**Comment by philipboomy** [comment]
My pleasure.

In this particular case
```
Town/City = London
County = Greater London
```

Another test could be
```
City = Ludlow
County = Shropshire
```

Here is a [list](https://en.wikipedia.org/wiki/Counties_of_England) of the counties if you need to do more checks.

**Comment by lindseydiloreto** [comment]
Excellent, that's very helpful.

Is "United Kingdom" the correct way to identify the Country? Or should that be "England"?

**Comment by philipboomy** [comment]
"United Kingdom"

**Comment by lindseydiloreto** [comment]
Alright, I just pushed **v3.3.4** with a patch for this. 👍

Please double-check it when you get a chance! Let me know if the UK addresses are now operating as expected.

**Comment by philipboomy** [comment]
It seems to be working correctly now. Thanks for fix

**Comment by lindseydiloreto** [comment]
Excellent, thanks for confirming!
