### ISSUE TITLE
Address information in GraphQL as object an not only as string

### ISSUE THREAD

**Issue by mheob** [doublesecretagency/craft-smartmap#58]
Hey there,

I'm still quite new to Craft CMS development, especially in terms of using GraphQL. So, I am not sure if I am doing something wrong. I apologize if that is the case.

After my current attempts there is no way to get the underlying fields of the address (street, city, zip ...) in GraphQL. In the following query I get back a concatenated string for the address, similar to STREET, CITY ZIP:

```graphql
query {
  entries(site: "*", section: "retailer") {
    id
    ...on retailer_retailer_Entry {
      retailerAddress
    }
  }
}
```

My wish would be to have access to the individual fields here. For example:

```graphql
query {
  entries(site: "*", section: "retailer") {
    id
    ...on retailer_retailer_Entry {
      retailerAddress {
        street1
        zip
        city
        lat
        lng
      }
  }
}

```

Is such a thing possible?

**Comment by lindseydiloreto** [comment]
Hi @mheob, sorry for the late reply.

I am still fairly new to GraphQL myself. Smart Map currently has light support for GraphQL, although [full support is planned for the future](https://github.com/doublesecretagency/craft-smartmap/issues/59). 

I'm not sure whether or not your code snippet would work... I'm sure by now you've figured out some sort of solution. If you're still stuck, hopefully you can wait until full support is in place.

Hope that helps for now!

**Comment by mheob** [comment]
Hi @lindseydiloreto, thanks for the answer.

Yes, it is right that I use a workaround for now. But this is not a solution that I want to keep forever. So I am looking forward to the direct support of the SmartMap one day.

**Comment by wolfwohlwend** [comment]
+1 Yes, native GraphQL support would be a great addition! Looking forward.

**Comment by mheob** [comment]
If I understand it correctly this plugin is no more maintained. Some info about this in the `README` would be very nice.
It seems that this issue continues here: https://github.com/doublesecretagency/craft-googlemaps/issues/2

**Comment by lindseydiloreto** [comment]
Yes, that's correct. Since the new Google Maps plugin has launched (just a few days ago), we'll be migrating all issues over to that repo and marking this one as abandoned.

To stay up to date, subscribe to the replacement thread...

 - https://github.com/doublesecretagency/craft-googlemaps/issues/2
