### ISSUE TITLE
Support for Native GraphQL

### ISSUE THREAD

**Issue by wbrowar** [doublesecretagency/craft-smartmap#59]
Smart Maps has support for CraftQL. Can the work put behind supporting CraftQL be ported over to Craft’s native GraphQL?

**Comment by lindseydiloreto** [comment]
Excellent request. We will be adding full GraphQL support in the next major version (hopefully within the next few months).

**Comment by lindseydiloreto** [comment]
Now that the new Google Maps plugin has been released, we'll be migrating all relevant Smart Map issues over to that repo.

To stay up-to-date, subscribe to the replacement issue...

 - https://github.com/doublesecretagency/craft-googlemaps/issues/2
