### ISSUE TITLE
FR - Opportunity to set default country for backend address search

### ISSUE THREAD

**Issue by philipboomy** [doublesecretagency/craft-smartmap#61]
Just a friendly note that if there is a chance in the future to implement this then I think it could be useful. In my particular scenario then it means the editors will save a lot time by jumping straight to post code and street address.

Not sure whats best, via a config file or just simple "default" value in the field.

**Comment by lindseydiloreto** [comment]
Sounds interesting! I'll give it some thought... no idea when it'll get added, or what form it will take. But we'll keep this thread open until then. 👍

Thanks for the FR!

**Comment by lindseydiloreto** [comment]
So I hadn't quite approached this issue yet, but @carlcs beat me to it! He filed a [pull request](https://github.com/doublesecretagency/craft-googlemaps/pull/18) on the new Google Maps plugin, which basically covers your original feature request!

As I noted in the PR thread, I plan to do a little more tweaking before pushing the new feature live. Mainly, I want to change where the language control settings is located.

Expect to see this feature added to Google Maps within the next 2 - 4 weeks! 🙂

**Comment by lindseydiloreto** [comment]
Following up, this was included in the [v4.0.5](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.0.5) release. 👍 

For more information, take a look at the [`fieldParams`](https://plugins.doublesecretagency.com/google-maps/getting-started/config/#fieldparams) config setting.
