### ISSUE TITLE
Render dynamic map using AJAX call?

### ISSUE THREAD

**Issue by tigerchick** [doublesecretagency/craft-smartmap#62]
I'm having trouble rendering a dynamic map when the template with the map is called via ajax (a static map works fine).
If I load the template normally then it renders fine. If I use jquery to call the template via ajax (when clicking a button to display a modal for example) the I just get "loading map".
I'm sure this is because the js for smartmap isn't getting loaded and this will be down to the template being pulled in via ajax.
However, I don't know how to force it to load. Any tips appreciated!

**Comment by lindseydiloreto** [comment]
Hi there. I'm not quite following what you are doing, it may be helpful to see your code.

I'd also recommend taking this conversation over to Craft Discord, where I may be able to better respond promptly. It sounds like you just trying to figure out how something works, not actually reporting a bug or feature request.

Feel free to ping me on Craft Discord (@lindseydiloreto), I'd be happy to help you troubleshoot it in real-time.
