### ISSUE TITLE
Control of where javascript is inserted

### ISSUE THREAD

**Issue by dustinwalker** [doublesecretagency/craft-smartmap#63]
If I use the {% js %} tag on a template that extends our main layout, that javascript isn't being inserted below the smartMap object—it's not defined when I try to set the style options.  As soon as that same code is in an include, it works.

If that issue is replicable, I'm curious if it would be possible to have more granular control of where that code is inserted. Possibly disabling the auto inserted and adding a template hook. That would also make it a bit easier to handle this in external javascript files.

Basically, our js is above smart map's code in this scenario:

```
{% extends '_layout.twig' %}

{% block content %}
	{{ craft.smartMap.map(locations, options) }}
{% endblock %}

{% js %}
	// our custom styles and stuff here
	smartMap.map["smartmap-mapcanvas-1"].setOptions({ styles: varHere });
{% endjs %}

```
But works like this:
```
{% extends '_layout.twig' %}

{% block content %}
	{% include '_partials/map'
{% endblock %}
```

And in our _partials/map.twig
```
{{ craft.smartMap.map(locations, options) }}
{% js %}
	smartMap.map["smartmap-mapcanvas-1"].setOptions({ styles: varHere });
{% endjs %}
```

Happy to give you access to the repo, just email me at dustin@astuteo.com or I can ping you on Discord if preferred. 

Smart Map is on version 3.3.4; Craft 3.5.11.1

Thanks!

**Comment by dustinwalker** [comment]
Hmm, this also seems to work so it's probably a Twig ordering issue: 

```
{% extends '_layout.twig' %}

{% block content %}
	{{ craft.smartMap.map(locations, options) }}
	{% js %}
		// our custom styles and stuff here
		smartMap.map["smartmap-mapcanvas-1"].setOptions({ styles: varHere });
	{% endjs %}
{% endblock %}
```

Would still be nice if a simple addition to know exactly where the generated javascript would be inserted.

**Comment by lindseydiloreto** [comment]
Hey Dustin, I'll ping you directly! 🙂
