### ISSUE TITLE
Instructions for using with Element API?

### ISSUE THREAD

**Issue by petehjfd** [doublesecretagency/craft-smartmap#64]
Hi

Are there any instructions for using SmartMap with Element API?

Specifically, I would like to:

- get a formatted address, either as a single line or two/three lines
- get the directions URL

To get the single line address in Twig, I would use `{{ entry.myAddressField }}` but using `$entry->myAddressField` with Element API obviously just returns the address object, e.g.:

```
"myAddressFddress": {
    "elementId": 41,
    "fieldId": 8,
    "handle": "location",
    "street1": "",
    "street2": "",
    "city": "Alloa",
    "state": "Clackmannanshire",
    "zip": "FK10 3TA",
    "country": "United Kingdom",
    "lat": "56.12245640",
    "lng": "-3.78118110",
    "coords": [
        "56.12245640",
        "-3.78118110"
    ],
    "distance": null
}
```

To get the two/three line address in Twig, I would use `{{ entry.myAddressField.format }}` but using `$entry->myAddressField->format` with Element API returns the following error:

```
"Getting unknown property: doublesecretagency\\smartmap\\models\\Address::format"
```

To get the directions in Twig, I would use `{{ entry.myFieldHandle.directionsUrl }}` but using `$entry->myAddressField->directionsUrl` with Element API returns the following error:

```
"Getting unknown property: doublesecretagency\\smartmap\\models\\Address::directionsUrl"
```

Any help would be appreciated.

Thanks

**Comment by lindseydiloreto** [comment]
That's because those are methods, not properties. 🙂

In PHP, you need to write them like this...

```
$entry->myAddressField->format()
$entry->myAddressField->directionsUrl()
```

Twig does you the "favor" of allowing you to call methods without the parenthesis (assuming you are passing no parameters). It's a helpful trick when working exclusively in Twig, but gets a little confusing when switching between Twig and PHP.

Hope that helps!
