### ISSUE TITLE
Pass an Attribute to Smartmap via Options

### ISSUE THREAD

**Issue by CreateSean** [doublesecretagency/craft-smartmap#68]
I would like to be able to pass an attribute to the rendered map something like this:

```twig
{% set options = {
    height: 300,
    mapTypeId: 'google.maps.MapTypeId.HYBRID'
   attr: { 'sprig', 
           'data-test':'test'
          }
} %}
```

Where `sprig` and `data-test` are attributes and `test` is the value of `data-test`

Is this possible? If not, would this be something that could be added?

**Comment by lindseydiloreto** [comment]
I've got another solution for you. We'll sort it out via DM. 👍
