### ISSUE TITLE
Craft field handles overlap issue with Smart Map field buttons

### ISSUE THREAD

**Issue by something-inc** [doublesecretagency/craft-smartmap#69]
There is an overlap issue with Smart Maps field buttons when the user setting `Show field handles in edit forms` in Craft is checked to show the field handle above the fields in the CP, the issue is shown in the image.

<img width="781" alt="Screenshot 2021-01-26 at 22 12 26" src="https://user-images.githubusercontent.com/78040293/105912649-b1521300-6023-11eb-9d36-6b4308e6d6f4.png">

**Comment by zizther** [comment]
Same issue with Craft 3.5.19 and Smart Maps 3.3.5

**Comment by lindseydiloreto** [comment]
Thanks for the heads up! 👍

**Comment by lindseydiloreto** [comment]
This has been fixed in the new Google Maps plugin **v4.0.1**.

 - https://github.com/doublesecretagency/craft-googlemaps/issues/7
