### ISSUE TITLE
Changed behaviour with `target` query param

### ISSUE THREAD

**Issue by engram-design** [doublesecretagency/craft-smartmap#70]
Back in the Craft 2 days, we wanted to be able to let users filter entries by an `address` Smart Map field with "fuzzy search". Like the below image.

![image](https://user-images.githubusercontent.com/1221575/108581952-64dcc780-7384-11eb-921e-d90b0c9a9133.png)

This seemingly worked with the following:
```
{% set params = {
    section: 'entriesChannel',
    orderBy: 'distance',
    limit: 10,
    addressField: {
        target: 'Melbourne',
        range: 100
    }
} %}

{% paginate craft.entries(params) as pageInfo, locations %}
```

For the above example we used `target` to supply anything about the address, which was pretty neat. However, this doesn't seem to work in the Craft 3 version. Diving into the code, the `target` attribute might've been incorrectly used by us in the first place, as it seems tied to coordinates?

Using `filter` would maybe be fine, but we don't know what the users are searching by to provide a key-value map of what to filter by. In addition, this adds a `andWhere` query so even if we provided all the properties, it would look for all that match.

Any ideas on what to do?

**Comment by lindseydiloreto** [comment]
Hey @engram-design! Just pinged you on Discord, let's get into the details over there. 👍

**Comment by lindseydiloreto** [comment]
Now that the Google Maps plugin has been released, go ahead and give it another shot with that version.

The new [proximity search](https://plugins.doublesecretagency.com/google-maps/proximity-search/) behavior is a bit more flexible now. Feel free to DM me if you hit any snags!
